import js from "@eslint/js";
import globals from "globals";
import jsxA11y from "eslint-plugin-jsx-a11y";
import reactHooks from "eslint-plugin-react-hooks";
import react from "eslint-plugin-react";

const maintainedFiles = [
  "src/admin/AdminShell.jsx",
  "src/admin/AdminShell.test.jsx",
  "src/admin/AdminSiteSettings.jsx",
  "src/admin/AdminSiteSettings.test.jsx",
  "src/admin/AdminSiteSettings.dom.test.jsx",
  "src/audio/CharacterMusicPreview.jsx",
  "src/audio/CharacterMusicPreview.dom.test.jsx",
  "src/modals/UserProfileCard.jsx",
  "src/modals/UserProfileCard.dom.test.jsx",
  "src/modals/FriendsModal.jsx",
  "src/modals/FriendsModal.test.jsx",
  "src/modals/FriendsModal.dom.test.jsx",
  "src/modals/MessageBoardModal.jsx",
  "src/modals/MessageBoardModal.dom.test.jsx",
  "src/modals/friends/FriendsOverlays.jsx",
  "src/modals/friends/FriendsOverlays.test.jsx",
  "src/modals/WarehouseModal.jsx",
  "src/modals/warehouse/WarehouseTargetModal.jsx",
  "src/modals/warehouse/WarehouseItemGrid.jsx",
  "src/modals/warehouse/useWarehouseInventory.js",
  "src/modals/warehouse/useWarehouseInventory.dom.test.jsx",
  "src/modals/modalComponents.dom.test.jsx",
  "src/modals/WatchModal.dom.test.jsx",
  "src/shared/CharacterBustPortrait.jsx",
  "src/shared/CharacterBustPortrait.dom.test.jsx",
  "src/home/components/PlayerPlaque.jsx",
  "src/home/components/PlayerPlaque.dom.test.jsx",
  "src/modals/ProfileResumeView.jsx",
  "src/modals/ProfileResumeView.dom.test.jsx",
  "src/room/PlayerInfo.jsx",
  "src/room/PlayerInfo.dom.test.jsx",
  "src/room/PlayerInfo.test.js",
  "src/shared/handbookPortraits.js",
  "src/shared/handbookPortraits.test.js",
  "src/shared/preloadAssets.js",
  "src/shared/preloadAssets.test.js",
  "tests/e2e/interface-polish*.js",
  "tests/e2e/interface-review-live*.js",
  "tests/e2e/fixtures/interface-polish.jsx",
  "src/home/MatchCharacter*.jsx",
  "src/home/useMatchCharacterSelection.js",
  "src/shared/characterFactions.js",
  "server/matchCharacterSelection*.js",
  "src/practice/**/*.js",
  "src/shared/localPractice.js",
  "src/shared/practiceBotPosition.js",
  "src/shared/practiceBotDecision.js",
  "server/localPracticeEngine*.js",
  "scripts/verify-practice-wasm.mjs",
  "tests/e2e/local-practice*.js",
  "tests/e2e/fixtures/local-practice.js",
  "tests/e2e/fixtures/local-practice-server.mjs",
  "scripts/playwrightTestDatabase.mjs",
  "scripts/start-e2e-environment.mjs",
  "scripts/start-e2e-client.mjs",
  "scripts/start-e2e-preview.mjs",
  "scripts/stop-test-processes.mjs",
  "scripts/stopTestProcesses.test.js",
  "scripts/run-full-e2e.mjs",
  "scripts/e2eIsolation.test.js",
  "tests/e2e/full-system*.js",
  "tests/e2e/ui-regressions.spec.js",
  "tests/e2e/team-match.spec.js",
  "tests/e2e/fixtures/team-match.jsx",
  "tests/e2e/fixtures/team-match-server.mjs",
  "tests/e2e/fixtures/home-onboarding-server.mjs",
  "scripts/start-stability-server.mjs",
  "server/httpErrors.js",
  "server/loginSessions.js",
  "src/app/modalDismissal.js",
  "src/modals/modalComponents.jsx",
  "src/modals/LeaderboardModal.jsx",
  "src/modals/WatchModal.jsx",
  "src/modals/PersonalizationModal.jsx"
];

export default [
  { ignores: ["dist/**", "node_modules/**", ".tmp/**", ".trellis/**", ".codex-temp/**", ".codex-run/**", ".worktrees/**", "public/engines/**"] },
  {
    files: maintainedFiles,
    ...js.configs.recommended,
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      parserOptions: { ecmaFeatures: { jsx: true } },
      globals: { ...globals.browser, ...globals.node }
    },
    plugins: {
      "jsx-a11y": jsxA11y,
      react,
      "react-hooks": reactHooks
    },
    rules: {
      ...js.configs.recommended.rules,
      ...jsxA11y.configs.recommended.rules,
      "react/jsx-uses-vars": "error",
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "error",
      "jsx-a11y/click-events-have-key-events": "off",
      "jsx-a11y/no-static-element-interactions": "off",
      "no-unused-vars": ["error", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }]
    }
  }
];
