ALTER TABLE "GameRecord" ADD COLUMN "rated" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "GameRecord" ADD COLUMN "matchSource" TEXT NOT NULL DEFAULT 'matchmaking';
ALTER TABLE "GameRecord" ADD COLUMN "blackRatingDelta" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "GameRecord" ADD COLUMN "whiteRatingDelta" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "GameRecord" ADD COLUMN "blackCoinsDelta" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "GameRecord" ADD COLUMN "whiteCoinsDelta" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "GameRecord" ADD COLUMN "blackRankDelta" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "GameRecord" ADD COLUMN "whiteRankDelta" INTEGER NOT NULL DEFAULT 0;
