upstream sigrikago_node {
    server 127.0.0.1:3001;
    keepalive 32;
}

server {
    listen 80;
    listen [::]:80;
    server_name sigrikago.com www.sigrikago.com;

    return 301 https://sigrikago.com$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name sigrikago.com www.sigrikago.com;

    ssl_certificate /etc/letsencrypt/live/sigrikago.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sigrikago.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    include /etc/nginx/snippets/sigrikago-routes.conf;
}
