
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.8.2
 * Query Engine version: 2060c79ba17c6bb9f5823312b6f6b7f4a845738e
 */
Prisma.prismaVersion = {
  client: "6.8.2",
  engine: "2060c79ba17c6bb9f5823312b6f6b7f4a845738e"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  username: 'username',
  passwordHash: 'passwordHash',
  role: 'role',
  status: 'status',
  banReason: 'banReason',
  bannedAt: 'bannedAt',
  rank: 'rank',
  rating: 'rating',
  wins: 'wins',
  losses: 'losses',
  coins: 'coins',
  blueGems: 'blueGems',
  selectedCharacter: 'selectedCharacter',
  selectedStoneDecoration: 'selectedStoneDecoration',
  ownedCharacters: 'ownedCharacters',
  ownedItems: 'ownedItems',
  itemPurchaseCounts: 'itemPurchaseCounts',
  itemEffects: 'itemEffects',
  ownedDecorations: 'ownedDecorations',
  ownedMusicIds: 'ownedMusicIds',
  musicSelections: 'musicSelections',
  onboardingRequired: 'onboardingRequired',
  onboardingAutoShownAt: 'onboardingAutoShownAt',
  onboardingCompletedAt: 'onboardingCompletedAt',
  welcomeMailNoticeShownAt: 'welcomeMailNoticeShownAt',
  sigrikaCandyUseCount: 'sigrikaCandyUseCount',
  sigrikaCandyPhase: 'sigrikaCandyPhase',
  sigrikaCandyOutcome: 'sigrikaCandyOutcome',
  sigrikaCandyRoomCode: 'sigrikaCandyRoomCode',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CaptureChallengeBestScalarFieldEnum = {
  userId: 'userId',
  captures: 'captures',
  characterId: 'characterId',
  costumeSnapshot: 'costumeSnapshot',
  bestRank: 'bestRank'
};

exports.Prisma.CaptureChallengeResultScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  captures: 'captures',
  rank: 'rank',
  breakthrough: 'breakthrough',
  createdAt: 'createdAt'
};

exports.Prisma.RecruitmentTaskScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  itemType: 'itemType',
  status: 'status',
  resultType: 'resultType',
  resultCharacterSlug: 'resultCharacterSlug',
  successRatePercent: 'successRatePercent',
  missStreakAtStart: 'missStreakAtStart',
  responseText: 'responseText',
  startedAt: 'startedAt',
  readyAt: 'readyAt',
  fastForwardedAt: 'fastForwardedAt',
  claimedAt: 'claimedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RecruitmentMissStreakScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  itemType: 'itemType',
  streak: 'streak',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserModeStatsScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  mode: 'mode',
  rating: 'rating',
  rank: 'rank',
  recentResults: 'recentResults',
  wins: 'wins',
  losses: 'losses',
  draws: 'draws',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LoginSessionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  refreshTokenHash: 'refreshTokenHash',
  revokedAt: 'revokedAt',
  expiresAt: 'expiresAt',
  lastSeenAt: 'lastSeenAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserCharacterScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  characterSlug: 'characterSlug',
  chainCount: 'chainCount',
  source: 'source',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.GachaPoolScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  enabled: 'enabled',
  permanent: 'permanent',
  startsAt: 'startsAt',
  endsAt: 'endsAt',
  singleDrawPrice: 'singleDrawPrice',
  tenDrawPrice: 'tenDrawPrice',
  featuredPrizeId: 'featuredPrizeId',
  featuredPrizeIds: 'featuredPrizeIds',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.GachaPrizeScalarFieldEnum = {
  id: 'id',
  poolId: 'poolId',
  type: 'type',
  targetId: 'targetId',
  quantity: 'quantity',
  probabilityBasisPoints: 'probabilityBasisPoints',
  enabled: 'enabled',
  name: 'name',
  imageUrl: 'imageUrl',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.GachaDrawScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  poolId: 'poolId',
  drawCount: 'drawCount',
  coinCost: 'coinCost',
  createdAt: 'createdAt'
};

exports.Prisma.GachaDrawRewardScalarFieldEnum = {
  id: 'id',
  drawId: 'drawId',
  poolId: 'poolId',
  prizeId: 'prizeId',
  drawIndex: 'drawIndex',
  type: 'type',
  targetId: 'targetId',
  quantity: 'quantity',
  unlockedQuantity: 'unlockedQuantity',
  duplicateQuantity: 'duplicateQuantity',
  blueGemsAdded: 'blueGemsAdded',
  chainAdded: 'chainAdded',
  coinsAdded: 'coinsAdded',
  createdAt: 'createdAt'
};

exports.Prisma.UserDecorationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  decorationSlug: 'decorationSlug',
  source: 'source',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserItemScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  itemId: 'itemId',
  quantity: 'quantity',
  source: 'source',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserItemEffectScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  effectKey: 'effectKey',
  effectValue: 'effectValue',
  source: 'source',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CostumeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  characterSlug: 'characterSlug',
  portraitUrl: 'portraitUrl',
  candyEffectPortraitUrl: 'candyEffectPortraitUrl',
  portraitScalePercent: 'portraitScalePercent',
  portraitOffsetXPercent: 'portraitOffsetXPercent',
  portraitOffsetYPercent: 'portraitOffsetYPercent',
  description: 'description',
  illustName: 'illustName',
  illustUrl: 'illustUrl',
  priceCoins: 'priceCoins',
  discountPercent: 'discountPercent',
  shopVisible: 'shopVisible',
  purchasable: 'purchasable',
  enabled: 'enabled',
  sortOrder: 'sortOrder',
  source: 'source',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserCostumeScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  costumeId: 'costumeId',
  source: 'source',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserCostumeEquipmentScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  characterSlug: 'characterSlug',
  costumeId: 'costumeId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserProgressLedgerScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  metric: 'metric',
  delta: 'delta',
  beforeValue: 'beforeValue',
  afterValue: 'afterValue',
  reason: 'reason',
  refType: 'refType',
  refId: 'refId',
  createdAt: 'createdAt'
};

exports.Prisma.MailboxBatchScalarFieldEnum = {
  id: 'id',
  adminUserId: 'adminUserId',
  adminUsername: 'adminUsername',
  targetMode: 'targetMode',
  recipientUserId: 'recipientUserId',
  sender: 'sender',
  title: 'title',
  body: 'body',
  attachmentType: 'attachmentType',
  attachmentItemId: 'attachmentItemId',
  attachmentQuantity: 'attachmentQuantity',
  includeFutureUsers: 'includeFutureUsers',
  deliveredCount: 'deliveredCount',
  skippedCount: 'skippedCount',
  createdAt: 'createdAt'
};

exports.Prisma.MailboxMessageScalarFieldEnum = {
  id: 'id',
  batchId: 'batchId',
  userId: 'userId',
  sender: 'sender',
  title: 'title',
  body: 'body',
  attachmentType: 'attachmentType',
  attachmentItemId: 'attachmentItemId',
  attachmentQuantity: 'attachmentQuantity',
  isRead: 'isRead',
  readAt: 'readAt',
  claimedAt: 'claimedAt',
  deletedAt: 'deletedAt',
  createdAt: 'createdAt'
};

exports.Prisma.UserRelationshipScalarFieldEnum = {
  id: 'id',
  ownerUserId: 'ownerUserId',
  targetUserId: 'targetUserId',
  type: 'type',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserProfileLikeScalarFieldEnum = {
  id: 'id',
  likerUserId: 'likerUserId',
  targetUserId: 'targetUserId',
  dayKey: 'dayKey',
  createdAt: 'createdAt'
};

exports.Prisma.UserReportScalarFieldEnum = {
  id: 'id',
  reporterUserId: 'reporterUserId',
  reportedUserId: 'reportedUserId',
  reporterUsername: 'reporterUsername',
  reportedUsername: 'reportedUsername',
  content: 'content',
  createdAt: 'createdAt'
};

exports.Prisma.GameRecordScalarFieldEnum = {
  id: 'id',
  roomCode: 'roomCode',
  blackUserId: 'blackUserId',
  whiteUserId: 'whiteUserId',
  blackName: 'blackName',
  whiteName: 'whiteName',
  blackCharacter: 'blackCharacter',
  whiteCharacter: 'whiteCharacter',
  blackCostumeId: 'blackCostumeId',
  whiteCostumeId: 'whiteCostumeId',
  blackCostumePortraitUrl: 'blackCostumePortraitUrl',
  whiteCostumePortraitUrl: 'whiteCostumePortraitUrl',
  blackCostumePortraitScalePercent: 'blackCostumePortraitScalePercent',
  whiteCostumePortraitScalePercent: 'whiteCostumePortraitScalePercent',
  blackCostumePortraitOffsetXPercent: 'blackCostumePortraitOffsetXPercent',
  whiteCostumePortraitOffsetXPercent: 'whiteCostumePortraitOffsetXPercent',
  blackCostumePortraitOffsetYPercent: 'blackCostumePortraitOffsetYPercent',
  whiteCostumePortraitOffsetYPercent: 'whiteCostumePortraitOffsetYPercent',
  resultText: 'resultText',
  winnerColor: 'winnerColor',
  resultReason: 'resultReason',
  rated: 'rated',
  matchSource: 'matchSource',
  blackRatingDelta: 'blackRatingDelta',
  whiteRatingDelta: 'whiteRatingDelta',
  blackCoinsDelta: 'blackCoinsDelta',
  whiteCoinsDelta: 'whiteCoinsDelta',
  blackRankDelta: 'blackRankDelta',
  whiteRankDelta: 'whiteRankDelta',
  moveCount: 'moveCount',
  mode: 'mode',
  snapshot: 'snapshot',
  snapshotVersion: 'snapshotVersion',
  createdAt: 'createdAt'
};

exports.Prisma.CharacterScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  name: 'name',
  description: 'description',
  portraitUrl: 'portraitUrl',
  portraitSource: 'portraitSource',
  acquisitionMethod: 'acquisitionMethod',
  cvName: 'cvName',
  cvUrl: 'cvUrl',
  illustName: 'illustName',
  illustUrl: 'illustUrl',
  source: 'source',
  palette: 'palette',
  enabled: 'enabled',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CharacterSkillScalarFieldEnum = {
  id: 'id',
  characterId: 'characterId',
  effectType: 'effectType',
  name: 'name',
  description: 'description',
  uses: 'uses',
  freeTurn: 'freeTurn',
  targetRule: 'targetRule',
  paramsJson: 'paramsJson',
  costType: 'costType',
  costValue: 'costValue',
  systemMessage: 'systemMessage',
  enabled: 'enabled',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SkillTraitScalarFieldEnum = {
  id: 'id',
  name: 'name',
  definition: 'definition',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DecorationScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  name: 'name',
  description: 'description',
  imageUrl: 'imageUrl',
  source: 'source',
  enabled: 'enabled',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ShopItemScalarFieldEnum = {
  id: 'id',
  name: 'name',
  category: 'category',
  targetId: 'targetId',
  itemTargetType: 'itemTargetType',
  stockQuantity: 'stockQuantity',
  priceCoins: 'priceCoins',
  discountPercent: 'discountPercent',
  purchasable: 'purchasable',
  enabled: 'enabled',
  sortOrder: 'sortOrder',
  description: 'description',
  imageUrl: 'imageUrl',
  illustName: 'illustName',
  illustUrl: 'illustUrl',
  source: 'source',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AchievementRewardAssetScalarFieldEnum = {
  id: 'id',
  type: 'type',
  name: 'name',
  description: 'description',
  imageUrl: 'imageUrl',
  text: 'text',
  targetType: 'targetType',
  targetId: 'targetId',
  amount: 'amount',
  enabled: 'enabled',
  deletedAt: 'deletedAt',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AchievementScalarFieldEnum = {
  id: 'id',
  key: 'key',
  name: 'name',
  content: 'content',
  conditionType: 'conditionType',
  conditionParams: 'conditionParams',
  rewardAssetId: 'rewardAssetId',
  enabled: 'enabled',
  deletedAt: 'deletedAt',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserAchievementScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  achievementId: 'achievementId',
  achievedAt: 'achievedAt',
  rewardGrantedAt: 'rewardGrantedAt'
};

exports.Prisma.AchievementCounterScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  metric: 'metric',
  targetId: 'targetId',
  value: 'value',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserAchievementEquipmentScalarFieldEnum = {
  userId: 'userId',
  titleAssetId: 'titleAssetId',
  badgeAssetId: 'badgeAssetId',
  nameplateAssetId: 'nameplateAssetId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MusicTrackSettingScalarFieldEnum = {
  id: 'id',
  displayName: 'displayName',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AdminAuditLogScalarFieldEnum = {
  id: 'id',
  adminUserId: 'adminUserId',
  action: 'action',
  targetType: 'targetType',
  targetId: 'targetId',
  beforeJson: 'beforeJson',
  afterJson: 'afterJson',
  createdAt: 'createdAt'
};

exports.Prisma.SiteSettingScalarFieldEnum = {
  key: 'key',
  value: 'value',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AnnouncementEntryScalarFieldEnum = {
  id: 'id',
  kind: 'kind',
  title: 'title',
  body: 'body',
  isPublished: 'isPublished',
  pinned: 'pinned',
  firstPublishedAt: 'firstPublishedAt',
  deletedAt: 'deletedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AnnouncementReadScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  announcementId: 'announcementId',
  readAt: 'readAt'
};

exports.Prisma.StoryScriptScalarFieldEnum = {
  id: 'id',
  key: 'key',
  title: 'title',
  triggerType: 'triggerType',
  triggerParamsJson: 'triggerParamsJson',
  draftStartNodeId: 'draftStartNodeId',
  draftInitialBoardJson: 'draftInitialBoardJson',
  draftNodesJson: 'draftNodesJson',
  isPublished: 'isPublished',
  publishedStartNodeId: 'publishedStartNodeId',
  publishedInitialBoardJson: 'publishedInitialBoardJson',
  publishedNodesJson: 'publishedNodesJson',
  firstPublishedAt: 'firstPublishedAt',
  publishedAt: 'publishedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.OnboardingStoryScriptScalarFieldEnum = {
  id: 'id',
  draftStartNodeId: 'draftStartNodeId',
  draftNodesJson: 'draftNodesJson',
  isPublished: 'isPublished',
  publishedStartNodeId: 'publishedStartNodeId',
  publishedNodesJson: 'publishedNodesJson',
  firstPublishedAt: 'firstPublishedAt',
  publishedAt: 'publishedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FeedbackMessageScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  username: 'username',
  content: 'content',
  createdAt: 'createdAt'
};

exports.Prisma.PersistedRoomScalarFieldEnum = {
  code: 'code',
  status: 'status',
  snapshot: 'snapshot',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  User: 'User',
  CaptureChallengeBest: 'CaptureChallengeBest',
  CaptureChallengeResult: 'CaptureChallengeResult',
  RecruitmentTask: 'RecruitmentTask',
  RecruitmentMissStreak: 'RecruitmentMissStreak',
  UserModeStats: 'UserModeStats',
  LoginSession: 'LoginSession',
  UserCharacter: 'UserCharacter',
  GachaPool: 'GachaPool',
  GachaPrize: 'GachaPrize',
  GachaDraw: 'GachaDraw',
  GachaDrawReward: 'GachaDrawReward',
  UserDecoration: 'UserDecoration',
  UserItem: 'UserItem',
  UserItemEffect: 'UserItemEffect',
  Costume: 'Costume',
  UserCostume: 'UserCostume',
  UserCostumeEquipment: 'UserCostumeEquipment',
  UserProgressLedger: 'UserProgressLedger',
  MailboxBatch: 'MailboxBatch',
  MailboxMessage: 'MailboxMessage',
  UserRelationship: 'UserRelationship',
  UserProfileLike: 'UserProfileLike',
  UserReport: 'UserReport',
  GameRecord: 'GameRecord',
  Character: 'Character',
  CharacterSkill: 'CharacterSkill',
  SkillTrait: 'SkillTrait',
  Decoration: 'Decoration',
  ShopItem: 'ShopItem',
  AchievementRewardAsset: 'AchievementRewardAsset',
  Achievement: 'Achievement',
  UserAchievement: 'UserAchievement',
  AchievementCounter: 'AchievementCounter',
  UserAchievementEquipment: 'UserAchievementEquipment',
  MusicTrackSetting: 'MusicTrackSetting',
  AdminAuditLog: 'AdminAuditLog',
  SiteSetting: 'SiteSetting',
  AnnouncementEntry: 'AnnouncementEntry',
  AnnouncementRead: 'AnnouncementRead',
  StoryScript: 'StoryScript',
  OnboardingStoryScript: 'OnboardingStoryScript',
  FeedbackMessage: 'FeedbackMessage',
  PersistedRoom: 'PersistedRoom'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
