from pathlib import Path
import re
s=Path('.codex-run/mobile-compact-options/index.html').read_text(encoding='utf-8')
s=s.replace('移动对弈 · 紧凑三版','移动对弈 · 双行纸卡样板')
s=re.sub(r'<nav>.*?</nav>','',s)
s=s.replace('<div class="stats">','<div class="footer"><div class="stats">').replace('</button></article>','</button></div></article>')
s=s.replace('完整手机比例：双方信息区＋接近满宽的正方形棋盘 · 无错落、无长空条','上下双方信息区均压为两行 · 独立纸卡与硬阴影 · 棋盘保持满宽正方形')
css='''
.phone.a .card{display:grid;grid-template-columns:58px minmax(0,1fr) 98px;grid-template-rows:52px 32px;grid-template-areas:'art id clock' 'footer footer footer';gap:6px;padding:2px 2px 4px;border:0;background:transparent;box-shadow:none;border-radius:0}
.phone .portrait{height:52px;min-height:0;overflow:visible;align-self:center}.phone .single .piece:first-child img{height:65px;bottom:0;width:110%;left:-5%}
.phone .identity{height:44px;align-self:center;padding:6px 8px;border:1px solid #5b4434;border-radius:7px;background:linear-gradient(#fffdf7,#f5ecdc);box-shadow:2px 2px 0 #8b7561;gap:5px;flex-wrap:wrap;align-content:center}.phone .identity .name{max-width:calc(100% - 16px);font-size:12px}.phone .rank{margin-left:15px;font-size:10px;width:100%;color:#79624f;line-height:1}
.phone .active .identity{background:linear-gradient(135deg,#3b3832,#252321);color:#fffaf0;border-color:#30281f;box-shadow:2px 2px #9b8167}.phone .active .rank{color:#e5d4bd}.phone .active .stone{box-shadow:0 0 0 1px #e0d0b7}
.phone.a .clock{height:52px;padding:5px 7px;border:1px solid #624a36;border-radius:7px;background:linear-gradient(#fffdf7,#f3ebdb);box-shadow:2px 2px #8b7561;grid-template-columns:1fr auto;grid-template-rows:1fr 4px;gap:3px}.phone .clock small{font-size:10px;max-width:20px;line-height:1.2}.phone .digits{font-size:25px;letter-spacing:-.6px;white-space:nowrap}.phone .digits em{font-size:10px;margin-left:2px}.phone .active .clock{background:linear-gradient(135deg,#fff1b7,#ffdf83);box-shadow:2px 2px #8b6630}.phone .track{background:#d4c6ad;height:4px}.phone .track i{background:#669989}.phone .active .track i{background:#be7638}
.footer{grid-area:footer;display:grid;grid-template-columns:repeat(3,49px) minmax(0,1fr);gap:5px;min-width:0}.phone .stats{display:contents}.phone .stats span{background:linear-gradient(#fffdf7,#f4eadb);border:1px solid #755b46;border-radius:6px;padding:4px;display:flex;align-items:center;justify-content:space-between;gap:2px;box-shadow:1px 2px #ac9680;font-size:10px}.phone .stats span+span{border-left:1px solid #755b46;padding-left:4px}.phone .stats span:last-child{background:linear-gradient(135deg,#ffe7ed,#f6bfd0);color:#9a294d;border-color:#a15c71;box-shadow:1px 2px #c08b9a}.phone .stats b{font-size:16px}
.phone .skill{grid-area:auto;grid-column:4;display:flex;padding:4px 6px;border:1px solid #5a8279;border-left:3px solid #669f91;border-radius:6px;background:linear-gradient(115deg,#eff9f1,#c8e8df);box-shadow:1px 2px #86aa9f;min-width:0;font-size:12px}.phone .skill b{background:#ffffff88;border-radius:4px;padding:2px 4px;font-size:11px}.phone .active .skill{background:linear-gradient(115deg,#fff2dd,#ffd0a9);border-color:#aa7850;border-left-color:#d89954;box-shadow:1px 2px #bf9776}.phone .skill.spent{background:linear-gradient(115deg,#eef3ef,#dae8e0);color:#53635d;border-color:#84988e;box-shadow:1px 2px #b3c3b9}.phone .skill.spent b{font-size:9px;padding:2px 3px}.phone .board{margin:10px 0}.phone .toolbar{margin-top:10px}.phone .toolbar button{border:1px solid #6e5540;box-shadow:1px 2px #b09c83;background:linear-gradient(#fffdf7,#f1e4d1)}
'''
s=s.replace('</style>',css+'</style>')
s=s.replace('剩余 1 次 ›','1')
a=s.index('<script>');s=s[:a]+'''<script>
function measure(){requestAnimationFrame(()=>{const c=document.querySelector('.card').getBoundingClientRect(),b=document.querySelector('.board').getBoundingClientRect();document.querySelector('.measure').textContent=`单侧信息区 ${Math.round(c.height)}px · 棋盘 ${Math.round(b.width)} × ${Math.round(b.height)}px`})}
document.querySelector('h2').textContent='两行排布 · 独立纸卡';document.querySelector('.desc').textContent='身份与时钟分列上方；三项统计和技能共用下排。阴影控制在 1–2px，和主界面纸卡质感呼应。';document.querySelector('select').onchange=e=>{document.querySelector('.phone').style.width=e.target.value+'px';measure()};document.querySelector('#single').onclick=()=>document.querySelectorAll('.portrait').forEach(p=>p.classList.toggle('single'));document.querySelector('#long').onclick=()=>{document.querySelectorAll('.name').forEach(n=>n.textContent=n.textContent.length>8?'moming':'用于检查排版的很长的用户名');document.querySelectorAll('.skill span').forEach(n=>n.textContent=n.textContent.length>9?'✧ 课定启动':'✧ 很长的角色技能名称')};document.querySelectorAll('.skill,.toolbar button').forEach(b=>b.onclick=()=>document.querySelector('dialog').showModal());document.querySelector('#close').onclick=()=>document.querySelector('dialog').close();document.querySelectorAll('.portrait').forEach(p=>p.classList.add('single'));document.querySelector('.skill').classList.add('spent');document.querySelector('.skill b').textContent='用尽';measure();</script></html>'''
Path('.codex-run/mobile-two-row/index.html').write_text(s,encoding='utf-8')
